<a href="https://colab.research.google.com/github/Kollamoram-Karthik/LampStack/blob/main/Copy_of_GANS_Assignment1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [3]:
import numpy as np

In [6]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
list2 = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(list2)
print(array2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Write a NumPy function to create an array with random values of shape [3,4]
def create_random_array():
  temp = np.random.rand(3,4)
  return temp


# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def create_zero_array():
  temp = np.zeros((3,4))
  return temp

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def create_ones_array():
  temp = np.ones((3,4))
  return temp


In [8]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def create_range_array(start, stop, step, method):
  if method == 'arange':
        my_array = np.arange(start, stop, step)
  elif method == 'linspace':
        my_array = np.linspace(start, stop, step)
  else:
        print('Invalid method specified')
        return None
  return my_array


### Basic array operations
- algebraic operations 
- logical operations

In [10]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [11]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def algebraic_ops(a,b):
  add = np.add(a,b)
  sub = np.subtract(a,b)
  mul = np.multiply(a,b)
  div = np.divide(a,b)

  return add, sub, mul, div

In [13]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum_axis_0(a):
    return np.sum(a, axis=0)

# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum_axis_1(a):
    return np.sum(a, axis=1)


In [14]:
# Write a NumPy function to reverse the array 'a' 
def reverse_array(a):
  return np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_array_axis_0(a):
  return np.flip(a, axis=0)


# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_axis_1(a):
  return np.flip(a, axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [19]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [21]:
# Write a NumPy function to sort the array 'a' 
def sort_array(a):
  return np.sort(a)


# Write a NumPy function to sort the array 'a' along axis=0
def sort_array_axis_0(a):
  return np.sort(a, axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
def sort_array_axis_1(a):
  return np.sort(a, axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_array_descend_axis_0(a):
  return np.sort(a,axis=0)[::-1]

In [29]:

# Write a NumPy function to argsort the array along axis=0
def argsort_array_axis_0(a):
    return np.argsort(a, axis=0)

# Write a NumPy function to argsort the array along axis=1
def argsort_array_axis_1(a):
    return np.argsort(a, axis=1)


In [28]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(a,b):
  return np.concatenate((a,b), axis=1)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenate_arrays_axis_0(a,b):
  return np.concatenate((a,b), axis=0)

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [34]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [39]:
# Write a NumPy function to get the Number of dimensions
def get_num_dimensions(a):
    return np.ndim(a)

# Write a NumPy function to get the Shape of the array
def get_array_shape(a):
    return np.shape(a)

# Write a NumPy function to get the Size of the array
def get_array_size(a):
    return np.size(a)

In [45]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_array(a):
    return np.reshape(a, (1, 9))

In [46]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
def add_new_axis_1(a):
    return a[np.newaxis, :]

In [41]:
def add_new_axis_2(a):
    return np.expand_dims(a, axis=0)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [41]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [42]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [51]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
def morethan4(a):
  condition = a > 4
  result = a[condition]
  print(result)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def even_morethan4(a):
  return a[(a > 4) & (a % 2 == 0)]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [49]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [48]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def new_array(a):
  b = a.copy()
  b += 1
  print(b)

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset